# Generated by Django 5.2 on 2025-05-10 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_first_name_user_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='full_name',
        ),
    ]
