# Generated by Django 5.2 on 2025-05-16 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_alter_country_options_alter_district_options_and_more'),
        ('users', '0009_remove_applicantprofile_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'verbose_name': 'Administrator profili', 'verbose_name_plural': 'Administrator profillari'},
        ),
        migrations.AlterModelOptions(
            name='applicantprofile',
            options={'verbose_name': 'Abituriyent profili', 'verbose_name_plural': 'Abituriyent profillari'},
        ),
        migrations.AlterModelOptions(
            name='phoneverification',
            options={'verbose_name': 'Telefonni tasdiqlash', 'verbose_name_plural': 'Telefonni tasdiqlashlar'},
        ),
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'verbose_name': 'Xodim profili', 'verbose_name_plural': 'Xodim profillari'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/admins/photos/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Yashash manzili'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='birth_date',
            field=models.DateField(verbose_name='Tug‘ilgan sana'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.country', verbose_name='Davlat'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.district', verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Jinsi'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/passports/images/', verbose_name='Pasport rasmi'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Millati'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='other_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Otasining ismi'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='passport_file',
            field=models.FileField(blank=True, null=True, upload_to='users/passports/files/', verbose_name='Pasport fayli (PDF)'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='passport_series',
            field=models.CharField(max_length=50, verbose_name='Pasport seriyasi va raqami'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='pinfl',
            field=models.CharField(max_length=255, verbose_name='JShShIR (PINFL)'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.region', verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'APPLICANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='code',
            field=models.CharField(max_length=6, verbose_name='Tasdiqlash kodi'),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/staffs/photos/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='To‘liq ismi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff huquqi bormi?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Tasdiqlanganmi?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('APPLICANT', 'Ariza topshiruvchi'), ('STAFF', 'Xodim')], default='APPLICANT', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram ID'),
        ),
    ]
