# Generated by Django 5.2 on 2025-05-16 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_adminprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneverification',
            options={'verbose_name': 'Telefonni tasdiqlash', 'verbose_name_plural': 'Tasdiqlash kodlari'},
        ),
    ]
