# Generated by Django 5.2 on 2025-05-16 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Filial', 'verbose_name_plural': 'Filiallar'},
        ),
        migrations.AlterModelOptions(
            name='educationform',
            options={'verbose_name': 'Taʼlim shakli', 'verbose_name_plural': 'Taʼlim shakllari'},
        ),
        migrations.AlterModelOptions(
            name='educationlevel',
            options={'verbose_name': 'Taʼlim darajasi', 'verbose_name_plural': 'Taʼlim darajalari'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Yo‘nalish', 'verbose_name_plural': 'Yo‘nalishlar'},
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Filial nomi'),
        ),
        migrations.AlterField(
            model_name='educationform',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Taʼlim shakli'),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Taʼlim darajasi'),
        ),
        migrations.AlterField(
            model_name='program',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Yo‘nalish kodi'),
        ),
        migrations.AlterField(
            model_name='program',
            name='contract_series',
            field=models.CharField(max_length=100, verbose_name='Shartnoma seriyasi'),
        ),
        migrations.AlterField(
            model_name='program',
            name='education_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.educationform', verbose_name='Taʼlim shakli'),
        ),
        migrations.AlterField(
            model_name='program',
            name='education_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.educationlevel', verbose_name='Taʼlim darajasi'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Yo‘nalish nomi'),
        ),
        migrations.AlterField(
            model_name='program',
            name='study_duration',
            field=models.CharField(max_length=100, verbose_name='O‘qish muddati'),
        ),
        migrations.AlterField(
            model_name='program',
            name='tuition_fee',
            field=models.CharField(max_length=255, verbose_name='Kontrakt summasi'),
        ),
    ]
