# Generated by Django 5.2 on 2025-06-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_branch_options_alter_educationform_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programs/program/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Yo‘nalish kodi'),
        ),
    ]
