# Generated by Django 5.2 on 2025-05-07 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diplom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('university_name', models.TextField()),
                ('graduation_year', models.CharField(max_length=4)),
                ('diploma_file', models.FileField(upload_to='diplomas/')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.district')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diploma', to=settings.AUTH_USER_MODEL)),
                ('education_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diploms.educationtype')),
                ('institution_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diploms.institutiontype')),
            ],
        ),
        migrations.CreateModel(
            name='TransferDiplom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.TextField()),
                ('transcript_file', models.FileField(upload_to='transcripts/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.country')),
                ('target_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diploms.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_diploma', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
