# Generated by Django 5.2 on 2025-05-10 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplom',
            name='diploma_file',
            field=models.FileField(upload_to='diploms/'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diplom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transferdiplom',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_diplom', to=settings.AUTH_USER_MODEL),
        ),
    ]
