# Generated by Django 5.2 on 2025-05-16 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploms', '0002_alter_diplom_diploma_file_alter_diplom_user_and_more'),
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='diplom',
            options={'verbose_name': 'Diplom', 'verbose_name_plural': 'Diplomlar'},
        ),
        migrations.AlterModelOptions(
            name='educationtype',
            options={'verbose_name': 'Taʼlim turi', 'verbose_name_plural': 'Taʼlim turlari'},
        ),
        migrations.AlterModelOptions(
            name='institutiontype',
            options={'verbose_name': 'Muassasa turi', 'verbose_name_plural': 'Muassasa turlari'},
        ),
        migrations.AlterModelOptions(
            name='transferdiplom',
            options={'verbose_name': 'Perevod diplomi', 'verbose_name_plural': 'Perevod diplomlari'},
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='diploma_file',
            field=models.FileField(upload_to='diploms/', verbose_name='Diplom fayli'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.district', verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='education_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diploms.educationtype', verbose_name='Taʼlim turi'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='graduation_year',
            field=models.CharField(max_length=4, verbose_name='Bitirgan yil'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='institution_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diploms.institutiontype', verbose_name='Muassasa turi'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.region', verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='serial_number',
            field=models.CharField(max_length=100, verbose_name='Diplom raqami'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='university_name',
            field=models.TextField(verbose_name='Universitet nomi'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diplom', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='educationtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Taʼlim turi'),
        ),
        migrations.AlterField(
            model_name='institutiontype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Muassasa turi'),
        ),
        migrations.AlterField(
            model_name='transferdiplom',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.country', verbose_name='Davlat'),
        ),
        migrations.AlterField(
            model_name='transferdiplom',
            name='target_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diploms.course', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='transferdiplom',
            name='transcript_file',
            field=models.FileField(upload_to='transcripts/', verbose_name='Transcript fayli'),
        ),
        migrations.AlterField(
            model_name='transferdiplom',
            name='university_name',
            field=models.TextField(verbose_name='Universitet nomi'),
        ),
        migrations.AlterField(
            model_name='transferdiplom',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_diplom', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
