# Generated by Django 5.2 on 2025-05-16 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('diploms', '0002_alter_diplom_diploma_file_alter_diplom_user_and_more'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Ariza', 'verbose_name_plural': 'Barcha Arizalar'},
        ),
        migrations.AlterField(
            model_name='application',
            name='admission_type',
            field=models.CharField(choices=[('regular', '1-kurs (Yangi qabul)'), ('transfer', 'Perevod (O‘qishni ko‘chirish)')], default='regular', max_length=20, verbose_name='Qabul turi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='application',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Shartnoma fayli'),
        ),
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diploms.course', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='application',
            name='diplom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diploms.diplom', verbose_name='Diplom'),
        ),
        migrations.AlterField(
            model_name='application',
            name='education_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.educationform', verbose_name='Taʼlim shakli'),
        ),
        migrations.AlterField(
            model_name='application',
            name='education_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.educationlevel', verbose_name='Taʼlim darajasi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program', verbose_name='Yo‘nalish'),
        ),
        migrations.AlterField(
            model_name='application',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='Ko‘rib chiquvchi xodim'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Yuborilgan'), ('review', 'Ko‘rib chiqilmoqda'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='application',
            name='transfer_diplom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diploms.transferdiplom', verbose_name='Perevod diplomi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan sana'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'APPLICANT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
